_G.ABTEST_LESS_OP = 1
_G.ABTEST_LESS_AND_EQUALS_OP = 2
_G.ABTEST_MORE_OP = 3
_G.ABTEST_MORE_AND_EQUALS_OP = 4
_G.ABTEST_EQUALS_OP = 5
_G.ABTEST_BETWEEN_OP = 6
_G.ABTEST_IN_OP = 7
_G.ABTEST_CONTAINS_OP = 8

_G.ABTEST_AND_EXP = 1
_G.ABTEST_OR_EXP = 2

_G.ABTEST_EXPRESSION_STRING_TYPE = "string"
_G.ABTEST_EXPRESSION_NUMBER_TYPE = "number"
_G.ABTEST_EXPRESSION_BOOL_TYPE = "bool"

